add_newline = true
format = """
$directory\
$custom\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$quarto\
$ruby\
$golang\
$rust\
$spack\
$cmd_duration\
$line_break\
$battery\
$shell\
$character"""

[character]
format = "$symbol "
success_symbol = "[󰜴](252)"
error_symbol = "[](196)"
vimcmd_symbol = ''

[directory]
style = 'fg:249 dimmed'
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = '~'
read_only = "󰌾 "
format = '[$read_only]($read_only_style)[$path]($style) '

[[battery.display]]
threshold = 10
style = 'bold 196'

[[battery.display]]
threshold = 20
style = 'bold 166'

[shell]
disabled = false
bash_indicator = '󱆃'

[cmd_duration]
show_milliseconds = true
format = " $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000


[git_branch]
style = "250"
symbol = " "
format = '[$symbol($branch)]($style) '

[git_metrics]
format = '([$added+]($added_style))([$deleted-]($deleted_style))'
added_style = 'dimmed 28'
deleted_style = 'dimmed 196'
ignore_submodules = true
disabled = false

[git_status]
format = '($all_status$ahead_behind($style))'
modified = "[${count}󰣕 ](210)"
untracked = "[${count} ](240)"
staged = "[${count}󱆭 ](157)"
ahead = "[${count} ](34)"
behind = "[${count} ](203)"
conflicted = "[${count}󰠠 ](196)"
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
deleted = '[${count}󰮈 ](245)'
renamed = "[${count}󱄍 ](202)"

[quarto]
style = '210 bold'
symbol = " "

[kubernetes]
disabled = false
style = '21'

[golang]
symbol = '󰟓  '

[ruby]
symbol = ' '

[custom.ssh_keys]
description = "show the number of keys loaded in the SSH agent"
when = "ssh-add -l | grep -v -q 'no identities'"
command = "ssh-add -l | grep -v 'no identities' | wc -l"
symbol = " "
style = "250"
format = "[$symbol($output)]($style) "

[custom.prompt_addition]
description = 'add the content of a PROMPT_ADDITION environment variable'
# if the environment variable is set
when = """ test -n "${PROMPT_ADDITION}" """
command = 'echo $PROMPT_ADDITION'
symbol = '󰴽 '
style = '19'

[custom.sshuttles]
description = 'list the nummber of sshuttle connection'
when = 'ls /tmp/$USER-sshuttle*.pid &>/dev/null'
command = 'ls /tmp/$USER-sshuttle*.pid | wc -l'
symbol = '󰌘 '
style = "250"
format = "[$symbol($output)]($style) "
